.PHONY: build test vet bench-build

build:
	go build -trimpath -o build/super-paqet ./cmd

test:
	go test -race ./...
	cd third_party/smux && go test -race -timeout 10m ./...
	cd third_party/kcp-go && go test -timeout 15m ./...

vet:
	go vet ./...
	cd third_party/smux && go vet ./...
	cd third_party/kcp-go && go vet ./...

bench-build:
	go build -o build/spq-bench ./cmd/bench
